### ISSUE TITLE
Enhancement: A win/lose screen , new gamemode

### ISSUE THREAD

**Issue by tuo65794** [cis3296s24/US-City-Guesser#31]
While testing your code, on your public host website and running locally on my laptop(Window). After winning, there isn't a clear way to know if you win. 

Maybe an alert or a screen that say you will. 

Another feature is that you could add a game mode where you only have 10 guesses and if you don't get it in 10 guesses, you lose. Similarly like Wordle.

**Comment by levinoscar** [comment]
Hi. My bad we just saw your message. We were able to display a confetti with the message of the "Congrats" page with the correct answer once you get the targeted city. It goes straight to the new game right away. :)
