### ISSUE TITLE
Confusing 

### ISSUE THREAD

**Issue by timo1k** [cis3296s24/US-City-Guesser#56]
Cool Game! I was a bit confused as to what to do at first but I read the instructions on the readme and was able to understand what to do; maybe add the instructions on how to start the game on the web Info page as well (type in a city to get the first pinpoint on the map)

**Comment by levinoscar** [comment]
Hi. There's two options you could do. The first is the easiest option is use the link "https://djroos.com" and that should present you to the game right away and click out of the info page to play. The other options is going through clone like from VSC and using the commands like npm install & npm start depending on if you already have the NodeJS application running.
